term.setBackgroundColor(colors.white)
term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.black)
print("running installer.lua...")
term.setBackgroundColor(colors.red)
term.setCursorPos(1,3)
term.write("          ")
os.sleep(1)
term.setBackgroundColor(colors.green)
term.setCursorPos(1,3)

term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
term.write(" ")
os.sleep(0.5)
